"""
Orchestrator Service for the Hybrid Blockchain System

This service acts as the central hub, connecting the following components:
1. IoT Data Source: Receives raw data from devices.
2. ML Privacy Filter: Calls the ML service to analyze data sensitivity.
3. Hyperledger Fabric: Stores the full, sensitive IoT data.
4. Ethereum Blockchain: Registers a public, redacted version of the data metadata.
"""

import os
import json
from flask import Flask, request, jsonify
from flask_cors import CORS
from flask_socketio import SocketIO, emit
from dotenv import load_dotenv
# Fabric SDK imports - commented out due to dependency issues
# We'll use REST API calls to Fabric instead
# from fabric_sdk_py.client import FabricClient
# from fabric_sdk_py.common.error import ChaincodeException
import requests
import hashlib
from web3 import Web3
from datetime import datetime
import threading
import time
from twin_manager import TwinManager
from outbox import Outbox
import contract_registry
import fabric_client

# Load environment variables from .env file
load_dotenv()

# --- Configuration ---
# ML Privacy Filter service endpoint
PRIVACY_FILTER_URL = os.getenv("PRIVACY_FILTER_URL", "http://127.0.0.1:5001/filter_data")

def get_windows_host_ip():
    """
    Parses the WSL resolv.conf file to get the Windows host IP address.
    This is necessary for services inside WSL to connect to services on the host.
    """
    try:
        # This file is auto-generated by WSL and contains the host's IP
        with open("/etc/resolv.conf") as f:
            for line in f:
                if line.strip().startswith("nameserver"):
                    return line.split()[1]
    except FileNotFoundError:
        # This will happen if not running in a standard WSL environment
        return None

# Ethereum node connection
# Since Ganache is running in Docker with port mapping, we can use localhost
ganache_host = "127.0.0.1"
print(f"Using localhost for Ganache connection")

GANACHE_URL = os.getenv("GANACHE_URL", f"http://{ganache_host}:8545")
print(f"Attempting to connect to Ganache at: {GANACHE_URL}")
web3 = Web3(Web3.HTTPProvider(GANACHE_URL))

# --- Ethereum Contract Configuration ---
# Path to the Truffle contract artifact, relative to the current script
CONTRACT_ARTIFACT_PATH = os.path.abspath(os.path.join(
    os.path.dirname(__file__),
    '..', 'blockchain', 'setup', 'ethereum', 'build', 'contracts', 'IoTDataRegistry.json'
))

iot_data_registry_contract = None
IOT_DATA_REGISTRY_ADDRESS = None
CONTRACT_RESOLUTION = None

# Resolved through contract_registry — the SINGLE selection rule shared with the
# experiments. Previously this module used networks[-1] while exp3_gas_real.py
# used max(key=int); when those diverge, the gas experiment measures one contract
# while the latency and exactly-once experiments anchor to another, inside what is
# reported as one consolidated run.
#
# Startup is refused if the resolved address holds no bytecode. That state means
# the artifact is stale relative to the running chain (a Ganache restart without a
# redeploy). Continuing would surface later as an opaque failure inside the relay
# worker, after the request has already been acknowledged with 202.
try:
    CONTRACT_RESOLUTION = contract_registry.resolve(
        CONTRACT_ARTIFACT_PATH, w3=web3, require_code=True)
    IOT_DATA_REGISTRY_ADDRESS = CONTRACT_RESOLUTION["address"]
    IOT_DATA_REGISTRY_ABI = CONTRACT_RESOLUTION["abi"]
    iot_data_registry_contract = web3.eth.contract(
        address=IOT_DATA_REGISTRY_ADDRESS, abi=IOT_DATA_REGISTRY_ABI)
    print(f"IoTDataRegistry at {IOT_DATA_REGISTRY_ADDRESS} "
          f"(network id {CONTRACT_RESOLUTION['network_id']}, "
          f"chain id {CONTRACT_RESOLUTION['chain_id']}, "
          f"{CONTRACT_RESOLUTION['code_size']} bytes of code, selected from "
          f"{CONTRACT_RESOLUTION['networks_in_artifact']} artifact entries)")
except FileNotFoundError:
    raise SystemExit(
        f"FATAL: contract artifact not found at {CONTRACT_ARTIFACT_PATH}. "
        f"Deploy first: npx truffle migrate --network development --reset")
except contract_registry.ContractResolutionError as e:
    raise SystemExit(f"FATAL: cannot resolve IoTDataRegistry.\n{e}")

# Fabric Configuration
FABRIC_CONN_PROFILE = os.path.join(os.path.dirname(__file__), 'connection-org1.json')
FABRIC_CHANNEL_NAME = os.getenv('FABRIC_CHANNEL_NAME', 'hiot')
FABRIC_CHAINCODE_NAME = os.getenv('FABRIC_CHAINCODE_NAME', 'iot-data')
FABRIC_USER_NAME = os.getenv('FABRIC_USER_NAME', 'user1')
FABRIC_USER_ORG = os.getenv('FABRIC_USER_ORG', 'Org1')
FABRIC_ORG_NAME = os.getenv('FABRIC_ORG_NAME', 'Org1')

def store_on_fabric(data_id, data):
    """Store the full record on Hyperledger Fabric via a REAL chaincode invoke.

    Delegates to fabric_client (peer CLI -> channel 'hiot', chaincode 'iot-data').
    Returns the real Fabric transaction id on success, or None on failure. There
    is no longer any simulated/fabricated transaction id (see PHASE0_FINDINGS.md).
    """
    try:
        tx_id = fabric_client.store_iot_data(data_id, data)
        if tx_id:
            print(f"Stored on Fabric: id={data_id} txid={tx_id}")
        else:
            print(f"Fabric store returned no txid for id={data_id}")
        return tx_id
    except Exception as e:
        print(f"Failed to store on Fabric: {e}")
        return None

# --- Flask App Initialization ---
app = Flask(__name__)
CORS(app)  # Enable CORS for all routes
socketio = SocketIO(app, cors_allowed_origins="*")

# Store active digital twins and their real-time data
active_twins = {}
twin_connections = set()

# Initialize Twin Manager for lifecycle management
twin_manager = TwinManager()

# --- Transactional outbox + relay worker (Phase 2, Change 1) ---
OUTBOX_DB = os.getenv("OUTBOX_DB", os.path.join(os.path.dirname(__file__), "outbox.db"))


def _anchor_row(row):
    """Deliver one outbox row to Ethereum. Runs ONLY on the relay worker thread.

    NOTE: the deployed contract exposes registerData(bytes32,string,string); there
    is no registerAnchor(id,h) on chain. The commitment H(m) is passed as
    _dataHash and the redacted metadata as _metadata.
    """
    if iot_data_registry_contract is None:
        raise RuntimeError("IoTDataRegistry contract not loaded; cannot anchor")
    payload = json.loads(row["payload"]) if row["payload"] else {}
    data_id_str = payload.get("data_id") or row["twin_key"] or row["id"]
    metadata_str = json.dumps(payload.get("metadata", {}))
    data_id_bytes32 = hashlib.sha256(data_id_str.encode()).digest()

    # On-chain uniqueness guard. IoTDataRegistry.registerData REVERTS with
    # "Data ID already registered" if this _dataId exists. That is what upgrades
    # at-least-once relay delivery into an exactly-once EFFECT on the public
    # ledger: even if this process dies after broadcasting but before recording
    # the receipt, the retry cannot create a second anchor. Treat an existing
    # record as success, not as a delivery failure — otherwise the recovery path
    # would retry to exhaustion and mark a successfully anchored row 'failed'.
    if iot_data_registry_contract.functions.getDataOwner(data_id_bytes32).call() != \
            "0x0000000000000000000000000000000000000000":
        print(f"[outbox] {row['id']}: anchor already on chain, idempotent no-op")
        return "preexisting:already_registered"

    sender_account = web3.eth.accounts[0]
    web3.eth.default_account = sender_account
    try:
        tx_hash = iot_data_registry_contract.functions.registerData(
            data_id_bytes32,    # _dataId
            row["commitment"],  # _dataHash = H(m)
            metadata_str,       # _metadata (redacted view)
        ).transact()
    except Exception as e:
        if "already registered" in str(e).lower():
            return "preexisting:already_registered"
        raise
    receipt = web3.eth.wait_for_transaction_receipt(tx_hash)
    return receipt.transactionHash.hex()


outbox = Outbox(OUTBOX_DB, anchor_fn=_anchor_row)

# Start the relay unless we are the Werkzeug reloader's parent process (which
# would give two workers racing on the same queue).
if os.getenv("RELAY_DISABLED", "").lower() not in ("1", "true", "yes"):
    if not os.getenv("WERKZEUG_RUN_MAIN") or os.getenv("WERKZEUG_RUN_MAIN") == "true":
        outbox.start_relay()
        print(f"Outbox relay worker started (db={OUTBOX_DB}, "
              f"poll={outbox.poll_interval_s}s, max_attempts={outbox.max_attempts})")

# --- Idempotency Cache for Exactly-Once Semantics ---
# Maps idempotency_key -> {response, timestamp, ethereum_tx_hash, status}
# status can be: 'pending' (in-flight), 'complete' (finished)
idempotency_cache = {}
idempotency_lock = threading.Lock()
idempotency_conditions = {}  # Maps key -> threading.Condition for waiting
IDEMPOTENCY_CACHE_TTL = 3600  # Cache entries expire after 1 hour
IDEMPOTENCY_WAIT_TIMEOUT = 120  # Max seconds to wait for pending request

def get_idempotency_key(data: dict, explicit_key: str = None) -> str:
    """Generate or use an idempotency key for a request."""
    if explicit_key:
        return explicit_key
    # Generate key from data content hash
    data_str = json.dumps(data, sort_keys=True)
    return hashlib.sha256(data_str.encode()).hexdigest()

def acquire_idempotency_slot(key: str) -> tuple:
    """
    Try to acquire the right to process a request with this key.
    Returns (cached_response, should_process):
    - (response, False) if already processed - return cached response
    - (None, True) if this request should process
    - (None, False) if waited but timed out
    """
    with idempotency_lock:
        if key in idempotency_cache:
            entry = idempotency_cache[key]
            # Check if entry is expired
            if time.time() - entry['timestamp'] > IDEMPOTENCY_CACHE_TTL:
                del idempotency_cache[key]
                if key in idempotency_conditions:
                    del idempotency_conditions[key]
            elif entry['status'] == 'complete':
                # Already processed, return cached response
                return (entry['response'], False)
            elif entry['status'] == 'pending':
                # Another request is processing - we need to wait
                condition = idempotency_conditions.get(key)
                if condition:
                    # Wait for the pending request to complete
                    condition.wait(timeout=IDEMPOTENCY_WAIT_TIMEOUT)
                    # Check again after waiting
                    if key in idempotency_cache and idempotency_cache[key]['status'] == 'complete':
                        return (idempotency_cache[key]['response'], False)
                    # Timed out or failed, let this request try
                    pass
        
        # Mark this key as pending (we're going to process it)
        idempotency_cache[key] = {
            'response': None,
            'timestamp': time.time(),
            'ethereum_tx_hash': None,
            'status': 'pending'
        }
        idempotency_conditions[key] = threading.Condition(idempotency_lock)
        return (None, True)

def complete_idempotency(key: str, response: dict):
    """Mark a request as complete and store the response."""
    with idempotency_lock:
        idempotency_cache[key] = {
            'response': response,
            'timestamp': time.time(),
            'ethereum_tx_hash': response.get('ethereum_tx_hash'),
            'status': 'complete'
        }
        # Notify any waiting requests
        if key in idempotency_conditions:
            idempotency_conditions[key].notify_all()
        
        # Cleanup old entries periodically
        if len(idempotency_cache) > 10000:
            current_time = time.time()
            expired_keys = [k for k, v in idempotency_cache.items() 
                           if current_time - v['timestamp'] > IDEMPOTENCY_CACHE_TTL]
            for k in expired_keys:
                del idempotency_cache[k]
                if k in idempotency_conditions:
                    del idempotency_conditions[k]

def release_idempotency_slot(key: str):
    """Release a pending slot if processing failed."""
    with idempotency_lock:
        if key in idempotency_cache and idempotency_cache[key]['status'] == 'pending':
            del idempotency_cache[key]
        if key in idempotency_conditions:
            idempotency_conditions[key].notify_all()
            del idempotency_conditions[key]

@app.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint.

    Reports the contract this process is actually anchoring to. Experiments record
    it in their provenance so that a run using a different contract from another
    experiment in the same consolidation is detectable after the fact
    (consolidate_results.py cross-checks these).
    """
    return jsonify({
        "status": "healthy",
        "ethereum_connected": web3.is_connected(),
        "contract_addr": IOT_DATA_REGISTRY_ADDRESS,
        "network_id": (CONTRACT_RESOLUTION or {}).get("network_id"),
        "chain_id": (CONTRACT_RESOLUTION or {}).get("chain_id"),
        "outbox_db": OUTBOX_DB,
    }), 200

@app.route('/ingest_data', methods=['POST'])
def ingest_data():
    """
    Main endpoint to ingest raw IoT data and orchestrate the full workflow.
    Implements exactly-once semantics via idempotency key.
    """
    raw_iot_data = request.get_json()
    if not raw_iot_data:
        return jsonify({"error": "Invalid JSON payload"}), 400

    # Check for idempotency key (from header or generate from data)
    idempotency_key = request.headers.get('X-Idempotency-Key')
    if not idempotency_key:
        # Generate key from data content for implicit idempotency
        idempotency_key = get_idempotency_key(raw_iot_data)
    
    # Try to acquire the right to process this request (handles concurrent duplicates)
    cached_response, should_process = acquire_idempotency_slot(idempotency_key)
    
    if cached_response:
        print(f"Idempotency hit: returning cached response for key {idempotency_key[:16]}...")
        cached_response = cached_response.copy()  # Don't modify cached version
        cached_response['idempotency_replay'] = True
        return jsonify(cached_response), 200
    
    if not should_process:
        # Waited for pending request but it failed/timed out
        release_idempotency_slot(idempotency_key)
        return jsonify({"error": "Request processing timed out"}), 503

    # Per-stage timing at REAL boundaries (Stage 4 instrumentation; replaces
    # exp1's fixed-fraction breakdown). Each stage is timed where it happens.
    t_ingress = time.perf_counter()

    # Step 1: Call the ML Privacy Filter
    try:
        # For this integration, we'll assume a default access level.
        # A real-world app would get this from an authentication system.
        privacy_filter_payload = {
            "iot_data": raw_iot_data,
            "requester_access_level": "user"
        }

        filter_response = requests.post(PRIVACY_FILTER_URL, json=privacy_filter_payload)
        filter_response.raise_for_status()  # Raise an exception for bad status codes

        filtered_result = filter_response.json()
        print("Received response from Privacy Filter:", filtered_result)
        
        # Extract the results from the privacy filter
        result = filtered_result.get('result', {})
        shareable_data = result.get('shareable_data')
        data_sensitivity = result.get('data_sensitivity')

        if not data_sensitivity:
            release_idempotency_slot(idempotency_key)
            return jsonify({"error": "Invalid or incomplete response from privacy filter"}), 500

        # shareable_data may legitimately be empty/absent: an all-sensitive record
        # has nothing publishable. That is NOT an error — it still commits
        # privately (Step 2) and simply produces no anchor (Step 3).
        if shareable_data is None:
            shareable_data = {}

        t_policy = time.perf_counter()

    except requests.exceptions.RequestException as e:
        print(f"ERROR: Could not connect to the Privacy Filter service: {e}")
        release_idempotency_slot(idempotency_key)
        return jsonify({"error": "Failed to connect to privacy filter service"}), 500

    # Step 2: Private commit — ALWAYS. Algorithm 1 line 21 / Eq (4) / Sec III-C:
    # the full payload always goes to the permissioned ledger, regardless of
    # sensitivity. The public/private distinction governs what enters the PUBLIC
    # metadata (Step 3), not whether Fabric is touched. (Phase 2, Change 2 —
    # the old `if data_sensitivity == 'sensitive'` guard meant non-sensitive
    # records were never persisted at rest.)
    data_id_str = raw_iot_data.get('id', 'unknown_id')
    try:
        fabric_tx_id = store_on_fabric(data_id_str, raw_iot_data)
    except Exception as e:
        print(f"ERROR: Fabric commit raised for id={data_id_str}: {e}")
        fabric_tx_id = None

    if not fabric_tx_id:
        # Fail loudly. Anchoring a commitment for a record that is not stored at
        # rest would publish a hash of data we cannot produce — worse than an
        # error. No silent continue (Phase 2: fail loudly, never fabricate).
        release_idempotency_slot(idempotency_key)
        return jsonify({
            "error": "Private commit to Fabric failed; record not persisted, nothing anchored",
            "data_id": data_id_str,
        }), 502

    t_fabric = time.perf_counter()

    # Step 3: Enqueue the public anchor in the transactional outbox and RETURN.
    # The anchor itself is delivered asynchronously by the relay worker — there is
    # no wait_for_transaction_receipt on this path (Phase 2, Change 1d).
    try:
        # Public metadata = redacted view only. An all-sensitive record has no
        # publishable fields, so nothing is anchored (anchor_required=False).
        metadata_obj = {k: v for k, v in shareable_data.items() if k != 'id'}
        anchor_required = bool(metadata_obj)

        # Commitment H(m) over the full raw record.
        data_hash = hashlib.sha256(json.dumps(raw_iot_data).encode()).hexdigest()
        if anchor_required:
            metadata_obj['fabricTxId'] = fabric_tx_id

        outbox.commit_and_enqueue(
            record_id=idempotency_key,
            commitment=data_hash,
            fabric_tx_id=fabric_tx_id,
            twin_key=data_id_str,
            version=raw_iot_data.get('version'),
            tau=data_sensitivity,
            payload={"data_id": data_id_str, "metadata": metadata_obj},
            anchor_required=anchor_required,
        )

        t_enqueue = time.perf_counter()
        timing_ms = {
            "policy_ms": round((t_policy - t_ingress) * 1000, 3),
            "fabric_ms": round((t_fabric - t_policy) * 1000, 3),
            "outbox_ms": round((t_enqueue - t_fabric) * 1000, 3),
            # Acknowledgement latency: t0 -> 200 OK. The client-visible number.
            "ack_ms": round((t_enqueue - t_ingress) * 1000, 3),
            "fabric_invoked": True,
            "anchor_enqueued": anchor_required,
        }

        final_response = {
            "status": "accepted",
            "message": ("Record committed privately; public anchor enqueued."
                        if anchor_required else
                        "Record committed privately; no publishable fields, no anchor."),
            "data_id": data_id_str,
            "data_hash": data_hash,
            "data_sensitivity": data_sensitivity,
            "fabric_tx_id": fabric_tx_id,
            "metadata": metadata_obj,
            "anchor_state": "pending" if anchor_required else "not_required",
            "outbox_id": idempotency_key,
            "timing_ms": timing_ms,
            "idempotency_key": idempotency_key,
            "idempotency_replay": False,
        }

        complete_idempotency(idempotency_key, final_response)
        return jsonify(final_response), 202

    except Exception as e:
        print(f"ERROR: outbox enqueue failed after private commit: {e}")
        # Reconciliation case: committed privately, never enqueued. Surfaced by
        # outbox.find_unanchored(). Fail loudly rather than pretend it anchored.
        release_idempotency_slot(idempotency_key)
        return jsonify({
            "error": "Committed to Fabric but failed to enqueue public anchor",
            "data_id": data_id_str,
            "fabric_tx_id": fabric_tx_id,
            "reconciliation_required": True,
        }), 500


@app.route('/anchor_status/<record_id>', methods=['GET'])
def anchor_status(record_id):
    """Completion-latency probe: has the relay delivered this record's anchor?"""
    row = outbox.get(record_id)
    if not row:
        if outbox.get_dedup(record_id):
            return jsonify({"outbox_id": record_id, "anchor_state": "not_required"}), 200
        return jsonify({"error": "unknown record"}), 404
    timing = outbox.timing_of(record_id) or {}
    return jsonify({
        "outbox_id": record_id,
        "anchor_state": row["state"],
        "attempts": row["attempts"],
        "eth_tx_hash": row["eth_tx_hash"],
        "created_at": row["created_at"],
        "delivery_started_at": row["delivery_started_at"],
        "delivered_at": row["delivered_at"],
        # total = queue_wait + anchor. Keep them separate: queue wait is relay
        # scheduling under load, anchor is the chain. Their sum is not "anchor
        # latency".
        "delivery_latency_ms": timing.get("total_ms"),
        "queue_wait_ms": timing.get("queue_wait_ms"),
        "anchor_ms": timing.get("anchor_ms"),
        "last_error": row["last_error"],
    }), 200


@app.route('/outbox_stats', methods=['GET'])
def outbox_stats():
    """Outbox health: queue depths, relay liveness, reconciliation set size."""
    return jsonify(outbox.stats()), 200

# --- Real-Time WebSocket Endpoints ---

@socketio.on('connect')
def handle_connect():
    """Handle client connection"""
    print(f"Client connected: {request.sid}")
    twin_connections.add(request.sid)
    emit('connection_status', {'status': 'connected', 'message': 'Connected to real-time twin updates'})
    
    # Send current active twins
    emit('active_twins', {'twins': list(active_twins.keys()), 'count': len(active_twins)})

@socketio.on('disconnect')
def handle_disconnect():
    """Handle client disconnection"""
    print(f"Client disconnected: {request.sid}")
    twin_connections.discard(request.sid)

@socketio.on('subscribe_twin')
def handle_subscribe(data):
    """Subscribe to a specific digital twin's updates"""
    twin_id = data.get('twin_id')
    if twin_id:
        print(f"Client {request.sid} subscribed to twin: {twin_id}")
        emit('subscription_confirmed', {'twin_id': twin_id, 'status': 'subscribed'})
        
        # Send current state if twin exists
        if twin_id in active_twins:
            emit('twin_state', {
                'twin_id': twin_id,
                'state': active_twins[twin_id],
                'timestamp': datetime.now().isoformat()
            })

@socketio.on('unsubscribe_twin')
def handle_unsubscribe(data):
    """Unsubscribe from a digital twin's updates"""
    twin_id = data.get('twin_id')
    if twin_id:
        print(f"Client {request.sid} unsubscribed from twin: {twin_id}")
        emit('subscription_confirmed', {'twin_id': twin_id, 'status': 'unsubscribed'})

@app.route('/stream_data', methods=['POST'])
def stream_data():
    """
    Endpoint for devices to stream real-time data.
    This updates the digital twin and broadcasts to connected clients.
    """
    try:
        data = request.get_json()
        if not data:
            return jsonify({"error": "Invalid JSON payload"}), 400
        
        twin_id = data.get('deviceId') or data.get('id', 'unknown')
        timestamp = datetime.now().isoformat()
        
        # Update twin state
        active_twins[twin_id] = {
            'data': data,
            'last_update': timestamp,
            'status': 'active'
        }
        
        # Broadcast to all connected clients
        # Use socketio.emit with app context
        with app.app_context():
            socketio.emit('twin_update', {
                'twin_id': twin_id,
                'data': data,
                'timestamp': timestamp
            })
        
        print(f"Real-time update for twin {twin_id} broadcasted to {len(twin_connections)} clients")
        
        return jsonify({
            "status": "success",
            "twin_id": twin_id,
            "timestamp": timestamp,
            "clients_notified": len(twin_connections)
        }), 200
    except Exception as e:
        print(f"Error in stream_data: {e}")
        import traceback
        traceback.print_exc()
        return jsonify({"error": str(e)}), 500

@app.route('/twins', methods=['GET'])
def get_active_twins():
    """Get all active digital twins"""
    return jsonify({
        "twins": active_twins,
        "count": len(active_twins),
        "connected_clients": len(twin_connections)
    }), 200

@app.route('/twins/<twin_id>', methods=['GET'])
def get_twin_state(twin_id):
    """Get current state of a specific digital twin"""
    if twin_id in active_twins:
        return jsonify({
            "twin_id": twin_id,
            "state": active_twins[twin_id]
        }), 200
    else:
        return jsonify({"error": "Twin not found"}), 404

# ===== TWIN LIFECYCLE MANAGEMENT API =====

@app.route('/api/twins', methods=['POST'])
def create_twin():
    """Create a new digital twin with full lifecycle management"""
    try:
        data = request.get_json()
        
        # Validate required fields
        if not data.get('twin_id'):
            return jsonify({"error": "twin_id is required"}), 400
        if not data.get('twin_type'):
            return jsonify({"error": "twin_type is required"}), 400
        if not data.get('initial_state'):
            return jsonify({"error": "initial_state is required"}), 400
        
        twin = twin_manager.create_twin(
            twin_id=data['twin_id'],
            twin_type=data['twin_type'],
            initial_state=data['initial_state'],
            metadata=data.get('metadata', {}),
            parent_id=data.get('parent_id')
        )
        
        # Also add to active_twins for real-time tracking
        active_twins[twin.twin_id] = {
            'data': twin.current_state,
            'last_update': twin.updated_at,
            'status': twin.status
        }
        
        # Broadcast twin creation
        with app.app_context():
            socketio.emit('twin_created', {
                'twin_id': twin.twin_id,
                'twin_type': twin.twin_type,
                'timestamp': twin.created_at
            })
        
        return jsonify({
            "status": "success",
            "message": "Twin created successfully",
            "twin": twin.to_dict()
        }), 201
        
    except ValueError as e:
        return jsonify({"error": str(e)}), 400
    except Exception as e:
        print(f"Error creating twin: {e}")
        import traceback
        traceback.print_exc()
        return jsonify({"error": str(e)}), 500

@app.route('/api/twins', methods=['GET'])
def list_twins():
    """List all digital twins with optional filters"""
    try:
        # Get query parameters for filtering
        filters = {}
        if request.args.get('status'):
            filters['status'] = request.args.get('status')
        if request.args.get('twin_type'):
            filters['twin_type'] = request.args.get('twin_type')
        if request.args.get('parent_id'):
            filters['parent_id'] = request.args.get('parent_id')
        
        twins = twin_manager.list_twins(filters)
        
        return jsonify({
            "status": "success",
            "count": len(twins),
            "twins": twins
        }), 200
        
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/twins/<twin_id>', methods=['GET'])
def get_twin_details(twin_id):
    """Get detailed information about a specific twin"""
    try:
        include_versions = request.args.get('include_versions', 'false').lower() == 'true'
        
        twin = twin_manager.get_twin(twin_id)
        if not twin:
            return jsonify({"error": "Twin not found"}), 404
        
        return jsonify({
            "status": "success",
            "twin": twin.to_dict(include_versions=include_versions)
        }), 200
        
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/twins/<twin_id>', methods=['PUT'])
def update_twin_full(twin_id):
    """Update a twin's state (full replacement)"""
    try:
        data = request.get_json()
        
        if not data.get('state'):
            return jsonify({"error": "state is required"}), 400
        
        success = twin_manager.update_twin(
            twin_id=twin_id,
            new_state=data['state'],
            metadata=data.get('metadata')
        )
        
        if not success:
            return jsonify({"error": "Twin not found"}), 404
        
        # Update active_twins for real-time
        twin = twin_manager.get_twin(twin_id)
        active_twins[twin_id] = {
            'data': twin.current_state,
            'last_update': twin.updated_at,
            'status': twin.status
        }
        
        # Broadcast update
        with app.app_context():
            socketio.emit('twin_update', {
                'twin_id': twin_id,
                'data': twin.current_state,
                'timestamp': twin.updated_at
            })
        
        return jsonify({
            "status": "success",
            "message": "Twin updated successfully",
            "twin": twin.to_dict()
        }), 200
        
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/twins/<twin_id>', methods=['PATCH'])
def update_twin_partial(twin_id):
    """Partially update a twin's state"""
    try:
        data = request.get_json()
        
        if not data.get('partial_state'):
            return jsonify({"error": "partial_state is required"}), 400
        
        success = twin_manager.patch_twin(
            twin_id=twin_id,
            partial_state=data['partial_state'],
            metadata=data.get('metadata')
        )
        
        if not success:
            return jsonify({"error": "Twin not found"}), 404
        
        # Update active_twins for real-time
        twin = twin_manager.get_twin(twin_id)
        active_twins[twin_id] = {
            'data': twin.current_state,
            'last_update': twin.updated_at,
            'status': twin.status
        }
        
        # Broadcast update
        with app.app_context():
            socketio.emit('twin_update', {
                'twin_id': twin_id,
                'data': twin.current_state,
                'timestamp': twin.updated_at
            })
        
        return jsonify({
            "status": "success",
            "message": "Twin patched successfully",
            "twin": twin.to_dict()
        }), 200
        
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/twins/<twin_id>', methods=['DELETE'])
def delete_twin_endpoint(twin_id):
    """Delete a twin (soft delete by default)"""
    try:
        soft_delete = request.args.get('soft', 'true').lower() == 'true'
        
        success = twin_manager.delete_twin(twin_id, soft_delete=soft_delete)
        
        if not success:
            return jsonify({"error": "Twin not found"}), 404
        
        # Remove from active_twins if hard delete
        if not soft_delete and twin_id in active_twins:
            del active_twins[twin_id]
        
        # Broadcast deletion
        with app.app_context():
            socketio.emit('twin_deleted', {
                'twin_id': twin_id,
                'soft_delete': soft_delete,
                'timestamp': datetime.now().isoformat()
            })
        
        return jsonify({
            "status": "success",
            "message": f"Twin {'soft' if soft_delete else 'hard'} deleted successfully"
        }), 200
        
    except Exception as e:
        return jsonify({"error": str(e)}), 500

# ===== VERSION CONTROL API =====

@app.route('/api/twins/<twin_id>/versions', methods=['GET'])
def get_twin_versions(twin_id):
    """Get version history for a twin"""
    try:
        twin = twin_manager.get_twin(twin_id)
        if not twin:
            return jsonify({"error": "Twin not found"}), 404
        
        return jsonify({
            "status": "success",
            "twin_id": twin_id,
            "current_version": twin.current_version - 1,
            "versions": twin.get_version_history()
        }), 200
        
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/twins/<twin_id>/versions/<int:version_number>', methods=['GET'])
def get_specific_version(twin_id, version_number):
    """Get a specific version of a twin"""
    try:
        twin = twin_manager.get_twin(twin_id)
        if not twin:
            return jsonify({"error": "Twin not found"}), 404
        
        version = twin.get_version(version_number)
        if not version:
            return jsonify({"error": "Version not found"}), 404
        
        return jsonify({
            "status": "success",
            "twin_id": twin_id,
            "version": version.to_dict()
        }), 200
        
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/twins/<twin_id>/rollback/<int:version_number>', methods=['POST'])
def rollback_twin(twin_id, version_number):
    """Rollback a twin to a specific version"""
    try:
        twin = twin_manager.get_twin(twin_id)
        if not twin:
            return jsonify({"error": "Twin not found"}), 404
        
        success = twin.rollback_to_version(version_number)
        if not success:
            return jsonify({"error": "Version not found"}), 404
        
        # Update active_twins
        active_twins[twin_id] = {
            'data': twin.current_state,
            'last_update': twin.updated_at,
            'status': twin.status
        }
        
        # Broadcast rollback
        with app.app_context():
            socketio.emit('twin_rollback', {
                'twin_id': twin_id,
                'version': version_number,
                'timestamp': twin.updated_at
            })
        
        return jsonify({
            "status": "success",
            "message": f"Twin rolled back to version {version_number}",
            "twin": twin.to_dict()
        }), 200
        
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/twins/<twin_id>/diff', methods=['GET'])
def get_version_diff(twin_id):
    """Compare two versions of a twin"""
    try:
        version1 = int(request.args.get('version1', 1))
        version2 = int(request.args.get('version2', 2))
        
        diff = twin_manager.get_version_diff(twin_id, version1, version2)
        if not diff:
            return jsonify({"error": "Twin or versions not found"}), 404
        
        return jsonify({
            "status": "success",
            "twin_id": twin_id,
            "diff": diff
        }), 200
        
    except Exception as e:
        return jsonify({"error": str(e)}), 500

# ===== GENEALOGY API =====

@app.route('/api/twins/<twin_id>/hierarchy', methods=['GET'])
def get_twin_hierarchy_endpoint(twin_id):
    """Get full hierarchy tree for a twin"""
    try:
        hierarchy = twin_manager.get_twin_hierarchy(twin_id)
        if not hierarchy:
            return jsonify({"error": "Twin not found"}), 404
        
        return jsonify({
            "status": "success",
            "hierarchy": hierarchy
        }), 200
        
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/twins/<twin_id>/ancestors', methods=['GET'])
def get_twin_ancestors_endpoint(twin_id):
    """Get all ancestors of a twin"""
    try:
        ancestors = twin_manager.get_twin_ancestors(twin_id)
        
        return jsonify({
            "status": "success",
            "twin_id": twin_id,
            "ancestors": ancestors,
            "count": len(ancestors)
        }), 200
        
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/twins/<twin_id>/descendants', methods=['GET'])
def get_twin_descendants_endpoint(twin_id):
    """Get all descendants of a twin"""
    try:
        descendants = twin_manager.get_twin_descendants(twin_id)
        
        return jsonify({
            "status": "success",
            "twin_id": twin_id,
            "descendants": descendants,
            "count": len(descendants)
        }), 200
        
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/twins/<twin_id>/children', methods=['POST'])
def add_child_twin(twin_id):
    """Add a child to a twin"""
    try:
        data = request.get_json()
        child_id = data.get('child_id')
        
        if not child_id:
            return jsonify({"error": "child_id is required"}), 400
        
        twin = twin_manager.get_twin(twin_id)
        if not twin:
            return jsonify({"error": "Parent twin not found"}), 404
        
        child = twin_manager.get_twin(child_id)
        if not child:
            return jsonify({"error": "Child twin not found"}), 404
        
        twin.add_child(child_id)
        child.parent_id = twin_id
        
        return jsonify({
            "status": "success",
            "message": "Child added successfully"
        }), 200
        
    except Exception as e:
        return jsonify({"error": str(e)}), 500

# ===== UTILITY API =====

@app.route('/api/twins/search', methods=['GET'])
def search_twins_endpoint():
    """Search twins by query"""
    try:
        query = request.args.get('q', '')
        if not query:
            return jsonify({"error": "Query parameter 'q' is required"}), 400
        
        results = twin_manager.search_twins(query)
        
        return jsonify({
            "status": "success",
            "query": query,
            "count": len(results),
            "results": results
        }), 200
        
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/twins/statistics', methods=['GET'])
def get_twin_statistics():
    """Get statistics about all twins"""
    try:
        stats = twin_manager.get_statistics()
        
        return jsonify({
            "status": "success",
            "statistics": stats
        }), 200
        
    except Exception as e:
        return jsonify({"error": str(e)}), 500


if __name__ == '__main__':
    # Note: For production, use a proper WSGI server like Gunicorn or uWSGI
    print("Starting Orchestrator with WebSocket support...")
    print("Real-time twin updates enabled on ws://0.0.0.0:5002")
    socketio.run(app, host='0.0.0.0', port=5002, debug=True, allow_unsafe_werkzeug=True)
