"""
Orchestrator Service for the Hybrid Blockchain System

This service acts as the central hub, connecting the following components:
1. IoT Data Source: Receives raw data from devices.
2. ML Privacy Filter: Calls the ML service to analyze data sensitivity.
3. Hyperledger Fabric: Stores the full, sensitive IoT data.
4. Ethereum Blockchain: Registers a public, redacted version of the data metadata.
"""

import os
import json
from flask import Flask, request, jsonify
from flask_cors import CORS
from dotenv import load_dotenv
# Fabric SDK imports - commented out due to dependency issues
# We'll use REST API calls to Fabric instead
# from fabric_sdk_py.client import FabricClient
# from fabric_sdk_py.common.error import ChaincodeException
import requests
import hashlib
from web3 import Web3

# Load environment variables from .env file
load_dotenv()

# --- Configuration ---
# ML Privacy Filter service endpoint
PRIVACY_FILTER_URL = os.getenv("PRIVACY_FILTER_URL", "http://127.0.0.1:5001/filter_data")

def get_windows_host_ip():
    """
    Parses the WSL resolv.conf file to get the Windows host IP address.
    This is necessary for services inside WSL to connect to services on the host.
    """
    try:
        # This file is auto-generated by WSL and contains the host's IP
        with open("/etc/resolv.conf") as f:
            for line in f:
                if line.strip().startswith("nameserver"):
                    return line.split()[1]
    except FileNotFoundError:
        # This will happen if not running in a standard WSL environment
        return None

# Ethereum node connection
# Since Ganache is running in Docker with port mapping, we can use localhost
ganache_host = "127.0.0.1"
print(f"Using localhost for Ganache connection")

GANACHE_URL = os.getenv("GANACHE_URL", f"http://{ganache_host}:8545")
print(f"Attempting to connect to Ganache at: {GANACHE_URL}")
web3 = Web3(Web3.HTTPProvider(GANACHE_URL))

# --- Ethereum Contract Configuration ---
# Path to the Truffle contract artifact, relative to the current script
CONTRACT_ARTIFACT_PATH = os.path.abspath(os.path.join(
    os.path.dirname(__file__),
    '..', 'blockchain', 'setup', 'ethereum', 'build', 'contracts', 'IoTDataRegistry.json'
))

iot_data_registry_contract = None
IOT_DATA_REGISTRY_ADDRESS = None

try:
    with open(CONTRACT_ARTIFACT_PATH) as f:
        artifact = json.load(f)
    
    IOT_DATA_REGISTRY_ABI = artifact['abi']
    
    # Get the address from the latest network deployment (e.g., Ganache)
    # This assumes the last network in the artifact is the one we want.
    if artifact.get('networks'):
        network_id = list(artifact['networks'].keys())[-1]
        IOT_DATA_REGISTRY_ADDRESS = artifact['networks'][network_id]['address']
        
        # Create contract instance
        iot_data_registry_contract = web3.eth.contract(
            address=IOT_DATA_REGISTRY_ADDRESS, 
            abi=IOT_DATA_REGISTRY_ABI
        )
        print(f"Successfully loaded contract 'IoTDataRegistry' at address: {IOT_DATA_REGISTRY_ADDRESS}")
    else:
        print("Warning: No network information found in contract artifact. Has it been deployed?")

except FileNotFoundError:
    print(f"ERROR: Contract artifact not found at {CONTRACT_ARTIFACT_PATH}")
except KeyError:
    print("ERROR: Could not find ABI or network address in contract artifact.")

# Fabric Configuration
FABRIC_CONN_PROFILE = os.path.join(os.path.dirname(__file__), 'connection-org1.json')
FABRIC_CHANNEL_NAME = os.getenv('FABRIC_CHANNEL_NAME', 'hiot')
FABRIC_CHAINCODE_NAME = os.getenv('FABRIC_CHAINCODE_NAME', 'iot-data')
FABRIC_USER_NAME = os.getenv('FABRIC_USER_NAME', 'user1')
FABRIC_USER_ORG = os.getenv('FABRIC_USER_ORG', 'Org1')
FABRIC_ORG_NAME = os.getenv('FABRIC_ORG_NAME', 'Org1')

def store_on_fabric(data_id, data):
    """Store data on Hyperledger Fabric using REST API or CLI."""
    try:
        # For now, we'll simulate Fabric storage
        # In production, this would use the Fabric REST API or SDK
        print(f"Storing data on Fabric with ID: {data_id}")
        # Return a simulated transaction ID
        return f"fabric_tx_{hashlib.sha256(json.dumps(data).encode()).hexdigest()[:16]}"
    except Exception as e:
        print(f"Failed to store on Fabric: {e}")
        return None

# --- Flask App Initialization ---
app = Flask(__name__)
CORS(app)  # Enable CORS for all routes

@app.route('/health', methods=['GET'])
def health_check():
    """Health check endpoint."""
    return jsonify({"status": "healthy", "ethereum_connected": web3.is_connected()}), 200

@app.route('/ingest_data', methods=['POST'])
def ingest_data():
    """
    Main endpoint to ingest raw IoT data and orchestrate the full workflow.
    """
    raw_iot_data = request.get_json()
    if not raw_iot_data:
        return jsonify({"error": "Invalid JSON payload"}), 400

    # Step 1: Call the ML Privacy Filter
    try:
        # For this integration, we'll assume a default access level.
        # A real-world app would get this from an authentication system.
        privacy_filter_payload = {
            "iot_data": raw_iot_data,
            "requester_access_level": "user"
        }

        filter_response = requests.post(PRIVACY_FILTER_URL, json=privacy_filter_payload)
        filter_response.raise_for_status()  # Raise an exception for bad status codes

        filtered_result = filter_response.json()
        print("Received response from Privacy Filter:", filtered_result)
        
        # Extract the results from the privacy filter
        result = filtered_result.get('result', {})
        shareable_data = result.get('shareable_data')
        data_sensitivity = result.get('data_sensitivity')

        if not shareable_data or not data_sensitivity:
            return jsonify({"error": "Invalid or incomplete response from privacy filter"}), 500

    except requests.exceptions.RequestException as e:
        print(f"ERROR: Could not connect to the Privacy Filter service: {e}")
        return jsonify({"error": "Failed to connect to privacy filter service"}), 500

    # Step 2: Conditionally store sensitive data in Hyperledger Fabric
    fabric_tx_id = None
    if data_sensitivity == 'sensitive':
        try:
            print("Sensitive data detected. Storing on Hyperledger Fabric...")
            
            # Store data on Fabric
            data_id_str = raw_iot_data.get('id', 'unknown_id')
            fabric_tx_id = store_on_fabric(data_id_str, raw_iot_data)
            
            if fabric_tx_id:
                print(f"Successfully stored sensitive data on Fabric. Transaction ID: {fabric_tx_id}")
            else:
                print("Warning: Failed to store on Fabric, continuing with Ethereum registration")

        except Exception as e:
            print(f"ERROR: An error occurred during the Fabric transaction: {e}")
            # Continue with Ethereum registration even if Fabric fails

    # Step 3: Register public metadata on Ethereum
    try:
        sender_account = web3.eth.accounts[0]
        web3.eth.default_account = sender_account
        print(f"Using sender account for Ethereum transaction: {sender_account}")

        # Use the shareable data for Ethereum registration
        data_id_str = shareable_data['id']
        data_id_bytes32 = hashlib.sha256(data_id_str.encode()).digest()
        metadata_str = json.dumps({key: val for key, val in shareable_data.items() if key != 'id'})

        print(f"Registering data on Ethereum. ID: {data_id_str}, Metadata: {metadata_str}")
        tx_hash = iot_data_registry_contract.functions.registerData(
            data_id_bytes32,
            metadata_str,
            data_sensitivity
        ).transact()

        print("Transaction sent. Waiting for receipt...")
        receipt = web3.eth.wait_for_transaction_receipt(tx_hash)
        print("Transaction successful! Receipt:", receipt)

        final_response = {
            "status": "success",
            "message": "Data processed and registered on the blockchain.",
            "ethereum_tx_hash": receipt.transactionHash.hex(),
            "data_id": data_id_str
        }
        return jsonify(final_response), 200

    except Exception as e:
        print(f"ERROR: An error occurred during the Ethereum transaction: {e}")
        return jsonify({"error": "Failed to register data on the Ethereum blockchain"}), 500


if __name__ == '__main__':
    # Note: For production, use a proper WSGI server like Gunicorn or uWSGI
    app.run(host='0.0.0.0', port=5002, debug=True)
